(function(g){var window=this;'use strict';var Zqb=function(a,b){a.jb("onAutonavCoundownStarted",b)},j6=function(a,b,c){g.hv(a.element,"ytp-suggestion-set",!!b.videoId);
var d=b.playlistId;c=b.Ug(c?c:"mqdefault.jpg");var e=null,f=null;b instanceof g.aT&&(b.lengthText?(e=b.lengthText||null,f=b.Qv||null):b.lengthSeconds&&(e=g.mH(b.lengthSeconds),f=g.mH(b.lengthSeconds,!0)));var h=!!d;d=h&&"RD"===g.lRa(d).type;var l=b instanceof g.aT?b.isLivePlayback:null,m=b instanceof g.aT?b.isUpcoming:null,n=b.author,p=b.shortViewCount,q=b.publishedTimeText,r=[],t=[];n&&r.push(n);p&&(r.push(p),t.push(p));q&&t.push(q);c={title:b.title,author:n,author_and_views:r.join(" \u2022 "),aria_label:b.ariaLabel||
g.AK("Watch $TITLE",{TITLE:b.title}),duration:e,timestamp:f,url:b.Jk(),is_live:l,is_upcoming:m,is_list:h,is_mix:d,background:c?"background-image: url("+c+")":"",views_and_publish_time:t.join(" \u2022 "),autoplayAlternativeHeader:b.Sr};b instanceof g.$S&&(c.playlist_length=b.playlistLength);a.update(c)},k6=function(a){var b=a.U(),c=b.D;
g.S.call(this,{I:"a",S:"ytp-autonav-suggestion-card",Y:{href:"{{url}}",target:c?b.W:"","aria-label":"{{aria_label}}","data-is-live":"{{is_live}}","data-is-list":"{{is_list}}","data-is-mix":"{{is_mix}}","data-is-upcoming":"{{is_upcoming}}"},V:[{I:"div",Ma:["ytp-autonav-endscreen-upnext-thumbnail","ytp-autonav-thumbnail-small"],Y:{style:"{{background}}"},V:[{I:"div",Y:{"aria-label":"{{timestamp}}"},Ma:["ytp-autonav-timestamp"],ya:"{{duration}}"},{I:"div",Ma:["ytp-autonav-live-stamp"],ya:"Live"},{I:"div",
Ma:["ytp-autonav-upcoming-stamp"],ya:"Upcoming"},{I:"div",S:"ytp-autonav-list-overlay",V:[{I:"div",S:"ytp-autonav-mix-text",ya:"Mix"},{I:"div",S:"ytp-autonav-mix-icon"}]}]},{I:"div",Ma:["ytp-autonav-endscreen-upnext-title","ytp-autonav-title-card"],ya:"{{title}}"},{I:"div",Ma:["ytp-autonav-endscreen-upnext-author","ytp-autonav-author-card"],ya:"{{author}}"},{I:"div",Ma:["ytp-autonav-endscreen-upnext-author","ytp-autonav-view-and-date-card"],ya:"{{views_and_publish_time}}"}]});this.J=a;this.suggestion=
null;this.j=c;this.Qa("click",this.onClick);this.Qa("keypress",this.onKeyPress)},l6=function(a,b){b=void 0===b?!1:b;
g.S.call(this,{I:"div",S:"ytp-autonav-endscreen-countdown-overlay"});var c=this;this.N=b;this.G=this.K=void 0;this.C=0;this.container=new g.S({I:"div",S:"ytp-autonav-endscreen-countdown-container"});g.J(this,this.container);this.container.Ja(this.element);b=a.U();var d=b.D;this.J=a;this.suggestion=null;this.onVideoDataChange("newdata",this.J.getVideoData());this.T(a,"videodatachange",this.onVideoDataChange);this.j=new g.S({I:"div",S:"ytp-autonav-endscreen-upnext-container",Y:{"aria-label":"{{aria_label}}",
"data-is-live":"{{is_live}}","data-is-list":"{{is_list}}","data-is-mix":"{{is_mix}}","data-is-upcoming":"{{is_upcoming}}"},V:[{I:"div",S:"ytp-autonav-endscreen-upnext-header"},{I:"div",S:"ytp-autonav-endscreen-upnext-alternative-header",ya:"{{autoplayAlternativeHeader}}"},{I:"a",S:"ytp-autonav-endscreen-link-container",Y:{href:"{{url}}",target:d?b.W:""},V:[{I:"div",S:"ytp-autonav-endscreen-upnext-thumbnail",Y:{style:"{{background}}"},V:[{I:"div",Y:{"aria-label":"{{timestamp}}"},Ma:["ytp-autonav-timestamp"],
ya:"{{duration}}"},{I:"div",Ma:["ytp-autonav-live-stamp"],ya:"Live"},{I:"div",Ma:["ytp-autonav-upcoming-stamp"],ya:"Upcoming"}]},{I:"div",S:"ytp-autonav-endscreen-video-info",V:[{I:"div",S:"ytp-autonav-endscreen-premium-badge"},{I:"div",S:"ytp-autonav-endscreen-upnext-title",ya:"{{title}}"},{I:"div",S:"ytp-autonav-endscreen-upnext-author",ya:"{{author}}"},{I:"div",S:"ytp-autonav-view-and-date",ya:"{{views_and_publish_time}}"},{I:"div",S:"ytp-autonav-author-and-view",ya:"{{author_and_views}}"}]}]}]});
g.J(this,this.j);this.j.Ja(this.container.element);d||this.T(this.j.Fa("ytp-autonav-endscreen-link-container"),"click",this.BS);this.J.createClientVe(this.container.element,this,115127);this.J.createClientVe(this.j.Fa("ytp-autonav-endscreen-link-container"),this,115128);this.overlay=new g.S({I:"div",S:"ytp-autonav-overlay"});g.J(this,this.overlay);this.overlay.Ja(this.container.element);this.B=new g.S({I:"div",S:"ytp-autonav-endscreen-button-container"});g.J(this,this.B);this.B.Ja(this.container.element);
this.cancelButton=new g.S({I:"button",Ma:["ytp-autonav-endscreen-upnext-button","ytp-autonav-endscreen-upnext-cancel-button",b.L("web_modern_buttons")?"ytp-autonav-endscreen-upnext-button-rounded":""],Y:{"aria-label":"Cancel autoplay"},ya:"Cancel"});g.J(this,this.cancelButton);this.cancelButton.Ja(this.B.element);this.cancelButton.Qa("click",this.B1,this);this.J.createClientVe(this.cancelButton.element,this,115129);this.playButton=new g.S({I:"a",Ma:["ytp-autonav-endscreen-upnext-button","ytp-autonav-endscreen-upnext-play-button",
b.L("web_modern_buttons")?"ytp-autonav-endscreen-upnext-button-rounded":""],Y:{href:"{{url}}",role:"button","aria-label":"Play next video"},ya:"Play Now"});g.J(this,this.playButton);this.playButton.Ja(this.B.element);this.playButton.Qa("click",this.BS,this);this.J.L("web_player_autonav_next_button_renderer")?(this.J.createServerVe(this.playButton.element,this.playButton,!0),(b=this.J.getVideoData())&&$qb(this,b)):this.J.createClientVe(this.playButton.element,this,115130);this.D=new g.Qu(function(){arb(c)},
500);
g.J(this,this.D);this.AS();this.T(a,"autonavvisibility",this.AS);this.J.L("web_autonav_color_transition")&&(this.T(a,"autonavchange",this.A1),this.T(a,"onAutonavCoundownStarted",this.L8))},m6=function(a){var b=a.J.hn(!0,a.J.isFullscreen());
g.hv(a.container.element,"ytp-autonav-endscreen-small-mode",a.Bg(b));g.hv(a.container.element,"ytp-autonav-endscreen-is-premium",!!a.suggestion&&!!a.suggestion.vK);g.hv(a.J.getRootNode(),"ytp-autonav-endscreen-cancelled-state",!a.J.sf());g.hv(a.J.getRootNode(),"countdown-running",a.Nk());g.hv(a.container.element,"ytp-player-content",a.J.sf());g.is(a.overlay.element,{width:b.width+"px"});if(!a.Nk()){a.J.sf()?brb(a,Math.round(crb(a)/1E3)):brb(a);b=!!a.suggestion&&!!a.suggestion.Sr;var c=a.J.sf()||!b;
g.hv(a.container.element,"ytp-autonav-endscreen-upnext-alternative-header-only",!c&&b);g.hv(a.container.element,"ytp-autonav-endscreen-upnext-no-alternative-header",c&&!b);g.tG(a.B,a.J.sf());g.hv(a.element,"ytp-enable-w2w-color-transitions",drb(a))}},arb=function(a){var b=crb(a),c=Math,d=c.min;
var e=a.C?Date.now()-a.C:0;c=d.call(c,e,b);brb(a,Math.ceil((b-c)/1E3));500>=b-c&&a.Nk()?a.select(!0):a.Nk()&&a.D.start()},crb=function(a){if(a.J.isFullscreen()){var b;
a=null==(b=a.J.getVideoData())?void 0:b.DB;return-1===a||void 0===a?8E3:a}return 0<=a.J.Bs()?a.J.Bs():g.OJ(a.J.U().experiments,"autoplay_time")||1E4},$qb=function(a,b){a.J.L("web_player_autonav_next_button_renderer");
b=b.v5;a.K=null==b?void 0:b.navigationEndpoint;b=null==b?void 0:b.trackingParams;a.playButton&&b&&a.J.setTrackingParams(a.playButton.element,b)},drb=function(a){var b;
return!(null==(b=a.J.getVideoData())||!b.watchToWatchTransitionRenderer)},brb=function(a,b){b=void 0===b?-1:b;
a=a.j.Fa("ytp-autonav-endscreen-upnext-header");g.qf(a);if(0<=b){b=String(b);var c="Up next in $SECONDS".match(RegExp("\\$SECONDS","gi"))[0],d="Up next in $SECONDS".indexOf(c);if(0<=d){a.appendChild(g.of("Up next in $SECONDS".slice(0,d)));var e=g.ef("span");g.bv(e,"ytp-autonav-endscreen-upnext-header-countdown-number");g.vf(e,b);a.appendChild(e);a.appendChild(g.of("Up next in $SECONDS".slice(d+c.length)));return}}g.vf(a,"Up next")},n6=function(a,b){g.S.call(this,{I:"div",
Ma:["html5-endscreen","ytp-player-content",b||"base-endscreen"]});this.created=!1;this.player=a},o6=function(a){g.S.call(this,{I:"div",
Ma:["ytp-upnext","ytp-player-content"],Y:{"aria-label":"{{aria_label}}"},V:[{I:"div",S:"ytp-cued-thumbnail-overlay-image",Y:{style:"{{background}}"}},{I:"span",S:"ytp-upnext-top",V:[{I:"span",S:"ytp-upnext-header",ya:"Up Next"},{I:"span",S:"ytp-upnext-title",ya:"{{title}}"},{I:"span",S:"ytp-upnext-author",ya:"{{author}}"}]},{I:"a",S:"ytp-upnext-autoplay-icon",Y:{role:"button",href:"{{url}}","aria-label":"Play next video"},V:[{I:"svg",Y:{height:"100%",version:"1.1",viewBox:"0 0 72 72",width:"100%"},
V:[{I:"circle",S:"ytp-svg-autoplay-circle",Y:{cx:"36",cy:"36",fill:"#fff","fill-opacity":"0.3",r:"31.5"}},{I:"circle",S:"ytp-svg-autoplay-ring",Y:{cx:"-36",cy:"36","fill-opacity":"0",r:"33.5",stroke:"#FFFFFF","stroke-dasharray":"211","stroke-dashoffset":"-211","stroke-width":"4",transform:"rotate(-90)"}},{I:"path",S:"ytp-svg-fill",Y:{d:"M 24,48 41,36 24,24 V 48 z M 44,24 v 24 h 4 V 24 h -4 z"}}]}]},{I:"span",S:"ytp-upnext-bottom",V:[{I:"span",S:"ytp-upnext-cancel"},{I:"span",S:"ytp-upnext-paused",
ya:"Autoplay is paused"}]}]});this.api=a;this.cancelButton=null;this.G=this.Fa("ytp-svg-autoplay-ring");this.C=this.notification=this.j=this.suggestion=null;this.D=new g.Qu(this.WG,5E3,this);this.B=0;var b=this.Fa("ytp-upnext-cancel");this.cancelButton=new g.S({I:"button",Ma:["ytp-upnext-cancel-button","ytp-button"],Y:{tabindex:"0","aria-label":"Cancel autoplay"},ya:"Cancel"});g.J(this,this.cancelButton);this.cancelButton.Qa("click",this.C1,this);this.cancelButton.Ja(b);this.cancelButton&&this.api.createClientVe(this.cancelButton.element,
this,115129);g.J(this,this.D);this.api.createClientVe(this.element,this,18788);b=this.Fa("ytp-upnext-autoplay-icon");this.T(b,"click",this.D1);this.api.createClientVe(b,this,115130);this.CS();this.T(a,"autonavvisibility",this.CS);this.T(a,"mdxnowautoplaying",this.x9);this.T(a,"mdxautoplaycanceled",this.y9);g.hv(this.element,"ytp-upnext-mobile",this.api.U().B)},erb=function(a,b){if(b)return b;
if(a.api.isFullscreen()){var c;a=null==(c=a.api.getVideoData())?void 0:c.DB;return-1===a||void 0===a?8E3:a}return 0<=a.api.Bs()?a.api.Bs():g.OJ(a.api.U().experiments,"autoplay_time")||1E4},frb=function(a,b){b=erb(a,b);
var c=Math,d=c.min;var e=(0,g.LD)()-a.B;c=d.call(c,e,b);b=0===b?1:Math.min(c/b,1);a.G.setAttribute("stroke-dashoffset",""+-211*(b+1));1<=b&&a.Nk()&&3!==a.api.getPresentingPlayerType()?a.select(!0):a.Nk()&&a.j.start()},p6=function(a){n6.call(this,a,"autonav-endscreen");
this.overlay=this.videoData=null;this.table=new g.S({I:"div",S:"ytp-suggestion-panel",V:[{I:"div",Ma:["ytp-autonav-endscreen-upnext-header","ytp-autonav-endscreen-more-videos"],ya:"More videos"}]});this.N=new g.S({I:"div",S:"ytp-suggestions-container"});this.videos=[];this.C=null;this.G=this.K=!1;this.B=new l6(this.player);g.J(this,this.B);this.B.Ja(this.element);a.getVideoData().Nf?this.j=this.B:(this.j=new o6(a),g.HU(this.player,this.j.element,4),g.J(this,this.j));this.overlay=new g.S({I:"div",
S:"ytp-autonav-overlay-cancelled-state"});g.J(this,this.overlay);this.overlay.Ja(this.element);this.D=new g.gL(this);g.J(this,this.D);g.J(this,this.table);this.table.Ja(this.element);this.table.show();g.J(this,this.N);this.N.Ja(this.table.element);this.hide()},q6=function(a){var b=a.sf();
b!==a.G&&(a.G=b,a.player.oa("autonavvisibility"),a.G?(a.B!==a.j&&a.B.hide(),a.table.hide()):(a.B!==a.j&&a.B.show(),a.table.show()))},r6=function(a,b){g.S.call(this,{I:"button",
Ma:["ytp-watch-on-youtube-button","ytp-button"],ya:"{{content}}"});this.J=a;this.buttonType=this.buttonType=b;this.e_();2===this.buttonType&&g.dv(this.element,"ytp-continue-watching-button");this.Qa("click",this.onClick);this.Qa("videodatachange",this.e_);g.tG(this,!0)},s6=function(a,b){n6.call(this,a,"embeds-lite-endscreen");
this.J=a;this.Re=b;this.J.createClientVe(this.element,this,156943);this.watchButton=new r6(a,2);g.J(this,this.watchButton);this.watchButton.Ja(this.element);this.hide()},grb=function(a){n6.call(this,a,"subscribecard-endscreen");
this.j=new g.S({I:"div",S:"ytp-subscribe-card",V:[{I:"img",S:"ytp-author-image",Y:{src:"{{profilePicture}}"}},{I:"div",S:"ytp-subscribe-card-right",V:[{I:"div",S:"ytp-author-name",ya:"{{author}}"},{I:"div",S:"html5-subscribe-button-container"}]}]});g.J(this,this.j);this.j.Ja(this.element);var b=a.getVideoData();this.subscribeButton=new g.BW("Subscribe",null,"Unsubscribe",null,!0,!1,b.yl,b.subscribed,"trailer-endscreen",null,a,!1);g.J(this,this.subscribeButton);this.subscribeButton.Ja(this.j.Fa("html5-subscribe-button-container"));
this.T(a,"videodatachange",this.Ra);this.Ra();this.hide()},t6=function(a){var b=a.U(),c=g.dL||g.nS?{style:"will-change: opacity"}:void 0,d=b.D,e=["ytp-videowall-still"];
b.B&&e.push("ytp-videowall-show-text");g.S.call(this,{I:"a",Ma:e,Y:{href:"{{url}}",target:d?b.W:"","aria-label":"{{aria_label}}","data-is-live":"{{is_live}}","data-is-list":"{{is_list}}","data-is-mix":"{{is_mix}}"},V:[{I:"div",S:"ytp-videowall-still-image",Y:{style:"{{background}}"}},{I:"span",S:"ytp-videowall-still-info",Y:{"aria-hidden":"true"},V:[{I:"span",S:"ytp-videowall-still-info-bg",V:[{I:"span",S:"ytp-videowall-still-info-content",Y:c,V:[{I:"span",S:"ytp-videowall-still-info-title",ya:"{{title}}"},
{I:"span",S:"ytp-videowall-still-info-author",ya:"{{author_and_views}}"},{I:"span",S:"ytp-videowall-still-info-live",ya:"Live"},{I:"span",S:"ytp-videowall-still-info-duration",ya:"{{duration}}"}]}]}]},{I:"span",Ma:["ytp-videowall-still-listlabel-regular","ytp-videowall-still-listlabel"],Y:{"aria-hidden":"true"},V:[{I:"span",S:"ytp-videowall-still-listlabel-icon"},"Playlist",{I:"span",S:"ytp-videowall-still-listlabel-length",V:[" (",{I:"span",ya:"{{playlist_length}}"},")"]}]},{I:"span",Ma:["ytp-videowall-still-listlabel-mix",
"ytp-videowall-still-listlabel"],Y:{"aria-hidden":"true"},V:[{I:"span",S:"ytp-videowall-still-listlabel-mix-icon"},"Mix",{I:"span",S:"ytp-videowall-still-listlabel-length",ya:" (50+)"}]}]});this.suggestion=null;this.B=d;this.api=a;this.j=new g.gL(this);g.J(this,this.j);this.Qa("click",this.onClick);this.Qa("keypress",this.onKeyPress);this.j.T(a,"videodatachange",this.onVideoDataChange);a.createServerVe(this.element,this);this.onVideoDataChange()},u6=function(a){n6.call(this,a,"videowall-endscreen");
var b=this;this.J=a;this.C=0;this.stills=[];this.D=this.videoData=null;this.G=this.N=!1;this.W=null;this.B=new g.gL(this);g.J(this,this.B);this.K=new g.Qu(function(){g.dv(b.element,"ytp-show-tiles")},0);
g.J(this,this.K);var c=new g.S({I:"button",Ma:["ytp-button","ytp-endscreen-previous"],Y:{"aria-label":"Previous"},V:[g.zG()]});g.J(this,c);c.Ja(this.element);c.Qa("click",this.H1,this);this.table=new g.qG({I:"div",S:"ytp-endscreen-content"});g.J(this,this.table);this.table.Ja(this.element);c=new g.S({I:"button",Ma:["ytp-button","ytp-endscreen-next"],Y:{"aria-label":"Next"},V:[g.AG()]});g.J(this,c);c.Ja(this.element);c.Qa("click",this.G1,this);a.getVideoData().Nf?this.j=new l6(a,!0):this.j=new o6(a);
g.J(this,this.j);g.HU(this.player,this.j.element,4);a.createClientVe(this.element,this,158789);this.hide()},v6=function(a){return g.IU(a.player)&&a.wC()&&!a.D},w6=function(a){var b=a.sf();
b!==a.N&&(a.N=b,a.player.oa("autonavvisibility"))},x6=function(a){n6.call(this,a,"watch-again-on-youtube-endscreen");
this.watchButton=new r6(a,1);g.J(this,this.watchButton);this.watchButton.Ja(this.element);g.vfb(a)&&(this.j=new g.x2(a),g.J(this,this.j),this.B=new g.S({I:"div",Ma:["ytp-watch-again-on-youtube-endscreen-more-videos-container"],Y:{tabIndex:"-1"},V:[this.j]}),g.J(this,this.B),this.j.Ja(this.B.element),this.B.Ja(this.element));a.createClientVe(this.element,this,156914);this.hide()},krb=function(a){g.UV.call(this,a);
var b=this;this.endScreen=null;this.B=this.j=this.C=this.D=!1;this.listeners=new g.gL(this);g.J(this,this.listeners);var c=a.U(),d=a.getVideoData();d=d&&0!==d.limitedPlaybackDurationInSeconds;g.LC(g.wS(c))&&d&&!g.DU(a)?(this.B=!0,this.endScreen=new s6(a,g.uU(a))):g.EU(a)?this.endScreen=new x6(a):hrb(a)?(this.D=!0,irb(this),this.j?this.endScreen=new p6(a):this.endScreen=new u6(a)):c.ih?this.endScreen=new grb(a):this.endScreen=new n6(a);g.J(this,this.endScreen);g.HU(a,this.endScreen.element,4);jrb(this);
this.listeners.T(a,"videodatachange",this.onVideoDataChange,this);this.listeners.T(a,g.uK("endscreen"),function(e){b.onCueRangeEnter(e)});
this.listeners.T(a,g.vK("endscreen"),function(e){b.onCueRangeExit(e)})},irb=function(a){var b=a.player.getVideoData();
if(!b||a.j===b.Al&&a.C===b.Nf)return!1;a.j=b.Al;a.C=b.Nf;return!0},hrb=function(a){a=a.U();
return a.Cd&&!a.ih},jrb=function(a){a.player.yf("endscreen");
var b=a.player.getVideoData();b=new g.tK(Math.max(1E3*(b.lengthSeconds-10),0),0x8000000000000,{id:"preload",namespace:"endscreen"});var c=new g.tK(0x8000000000000,0x8000000000000,{id:"load",priority:8,namespace:"endscreen"});a.player.qf([b,c])};
g.zU.prototype.Bs=g.ca(16,function(){return this.app.Bs()});
g.$0.prototype.Bs=g.ca(15,function(){return this.getVideoData().nU});
g.vU.prototype.vr=g.ca(14,function(a){this.oi().vr(a)});
g.$W.prototype.vr=g.ca(13,function(a){this.j!==a&&(this.j=a,this.Ra())});
g.gY.prototype.vr=g.ca(12,function(a){this.overflowButton&&this.overflowButton.vr(a)});
g.vU.prototype.wr=g.ca(11,function(a){this.oi().wr(a)});
g.eX.prototype.wr=g.ca(10,function(a){this.j!==a&&(this.j=a,this.Ra())});
g.gY.prototype.wr=g.ca(9,function(a){this.shareButton&&this.shareButton.wr(a)});
g.vU.prototype.cB=g.ca(8,function(a){this.oi().cB(a)});
g.uW.prototype.cB=g.ca(7,function(a){this.pQ!==a&&(this.pQ=a,this.Vp())});
g.vU.prototype.bB=g.ca(6,function(a){this.oi().bB(a)});
g.gY.prototype.bB=g.ca(5,function(a){this.oQ!==a&&(this.oQ=a,this.Up())});g.w(k6,g.S);k6.prototype.select=function(){this.J.xo(this.suggestion.videoId,this.suggestion.sessionData,this.suggestion.playlistId,void 0,void 0,this.suggestion.QC||void 0)&&this.J.logClick(this.element)};
k6.prototype.onClick=function(a){g.cV(a,this.J,this.j,this.suggestion.sessionData||void 0)&&this.select()};
k6.prototype.onKeyPress=function(a){switch(a.keyCode){case 13:case 32:a.defaultPrevented||(this.select(),a.preventDefault())}};g.w(l6,g.S);g.k=l6.prototype;g.k.fG=function(a){this.suggestion!==a&&(this.suggestion=a,j6(this.j,a),this.playButton.updateValue("url",this.suggestion.Jk()),m6(this))};
g.k.Nk=function(){return 0<this.C};
g.k.kB=function(){this.Nk()||(this.C=Date.now(),arb(this),Zqb(this.J,crb(this)),g.hv(this.J.getRootNode(),"countdown-running",this.Nk()))};
g.k.xw=function(){this.Qp();arb(this);var a=this.j.Fa("ytp-autonav-endscreen-upnext-header");a&&g.vf(a,"Up next")};
g.k.Qp=function(){this.Nk()&&(this.D.stop(),this.C=0)};
g.k.select=function(a){this.J.nextVideo(!1,void 0===a?!1:a);this.Qp()};
g.k.BS=function(a){g.cV(a,this.J)&&(a.currentTarget===this.playButton.element?this.J.logClick(this.playButton.element):a.currentTarget===this.j.Fa("ytp-autonav-endscreen-link-container")&&(a=this.j.Fa("ytp-autonav-endscreen-link-container"),this.J.logVisibility(a,!0),this.J.logClick(a)),this.J.L("web_player_autonav_next_button_renderer")&&this.K?(this.J.jb("innertubeCommand",this.K),this.Qp()):this.select())};
g.k.B1=function(){this.J.logClick(this.cancelButton.element);g.BU(this.J,!0);this.G&&this.J.jb("innertubeCommand",this.G)};
g.k.onVideoDataChange=function(a,b){this.J.L("web_player_autonav_next_button_renderer")&&$qb(this,b);var c;this.G=null==(c=b.T4)?void 0:c.command};
g.k.L8=function(a){if(drb(this)){var b=this.J.getVideoData().watchToWatchTransitionRenderer,c=null==b?void 0:b.fromColorPaletteDark;b=null==b?void 0:b.toColorPaletteDark;if(c&&b){var d=this.element;d.style.setProperty("--w2w-start-background-color",g.uH(c.surgeColor));d.style.setProperty("--w2w-start-primary-text-color",g.uH(c.primaryTitleColor));d.style.setProperty("--w2w-start-secondary-text-color",g.uH(c.secondaryTitleColor));d.style.setProperty("--w2w-end-background-color",g.uH(b.surgeColor));
d.style.setProperty("--w2w-end-primary-text-color",g.uH(b.primaryTitleColor));d.style.setProperty("--w2w-end-secondary-text-color",g.uH(b.secondaryTitleColor));d.style.setProperty("--w2w-animation-duration",a+"ms")}g.hv(this.element,"ytp-w2w-animate",!0)}};
g.k.A1=function(a){this.J.L("web_autonav_color_transition")&&2!==a&&g.hv(this.element,"ytp-w2w-animate",!1)};
g.k.AS=function(){var a=this.J.sf();this.N&&this.Ib!==a&&g.tG(this,a);m6(this);this.J.logVisibility(this.container.element,a);this.J.logVisibility(this.cancelButton.element,a);this.J.logVisibility(this.j.Fa("ytp-autonav-endscreen-link-container"),a);this.J.logVisibility(this.playButton.element,a)};
g.k.Bg=function(a){return 400>a.width||459>a.height};g.w(n6,g.S);g.k=n6.prototype;g.k.create=function(){this.created=!0};
g.k.destroy=function(){this.created=!1};
g.k.wC=function(){return!1};
g.k.sf=function(){return!1};
g.k.sX=function(){return!1};g.w(o6,g.S);g.k=o6.prototype;g.k.WG=function(){this.notification&&(this.D.stop(),this.Oc(this.C),this.C=null,this.notification.close(),this.notification=null)};
g.k.fG=function(a){this.suggestion=a;j6(this,a,"hqdefault.jpg")};
g.k.CS=function(){g.tG(this,this.api.sf());this.api.logVisibility(this.element,this.api.sf());this.api.logVisibility(this.Fa("ytp-upnext-autoplay-icon"),this.api.sf());this.cancelButton&&this.api.logVisibility(this.cancelButton.element,this.api.sf())};
g.k.G9=function(){window.focus();this.WG()};
g.k.kB=function(a){var b=this;this.Nk()||(g.UE("a11y-announce","Up Next "+this.suggestion.title),this.B=(0,g.LD)(),this.j=new g.Qu(function(){frb(b,a)},25),frb(this,a),Zqb(this.api,erb(this,a)));
g.fv(this.element,"ytp-upnext-autoplay-paused")};
g.k.hide=function(){g.S.prototype.hide.call(this)};
g.k.Nk=function(){return!!this.j};
g.k.xw=function(){this.Qp();this.B=(0,g.LD)();frb(this);g.dv(this.element,"ytp-upnext-autoplay-paused")};
g.k.Qp=function(){this.Nk()&&(this.j.dispose(),this.j=null)};
g.k.select=function(a){a=void 0===a?!1:a;if(this.api.U().L("autonav_notifications")&&a&&window.Notification&&"function"===typeof document.hasFocus){var b=Notification.permission;"default"===b?Notification.requestPermission():"granted"!==b||document.hasFocus()||(this.WG(),this.notification=new Notification("Up Next",{body:this.suggestion.title,icon:this.suggestion.Ug()}),this.C=this.T(this.notification,"click",this.G9),this.D.start())}this.Qp();this.api.nextVideo(!1,a)};
g.k.D1=function(a){!g.uf(this.cancelButton.element,a.target)&&g.cV(a,this.api)&&(this.api.sf()&&this.api.logClick(this.Fa("ytp-upnext-autoplay-icon")),this.select())};
g.k.C1=function(){this.api.sf()&&this.cancelButton&&this.api.logClick(this.cancelButton.element);g.BU(this.api,!0)};
g.k.x9=function(a){this.api.getPresentingPlayerType();this.show();this.kB(a)};
g.k.y9=function(){this.api.getPresentingPlayerType();this.Qp();this.hide()};
g.k.xa=function(){this.Qp();this.WG();g.S.prototype.xa.call(this)};g.w(p6,n6);g.k=p6.prototype;g.k.create=function(){n6.prototype.create.call(this);this.D.T(this.player,"appresize",this.LB);this.D.T(this.player,"onVideoAreaChange",this.LB);this.D.T(this.player,"videodatachange",this.onVideoDataChange);this.D.T(this.player,"autonavchange",this.DS);this.D.T(this.player,"onAutonavCancelled",this.E1);this.onVideoDataChange()};
g.k.show=function(){n6.prototype.show.call(this);(this.K||this.C&&this.C!==this.videoData.clientPlaybackNonce)&&g.BU(this.player,!1);g.IU(this.player)&&this.wC()&&!this.C?(q6(this),2===this.videoData.autonavState?3===this.player.getVisibilityState()?this.j.select(!0):this.j.kB():3===this.videoData.autonavState&&this.j.xw()):(g.BU(this.player,!0),q6(this));this.LB()};
g.k.hide=function(){n6.prototype.hide.call(this);this.j.xw();q6(this)};
g.k.LB=function(){var a=this.player.hn(!0,this.player.isFullscreen());q6(this);m6(this.B);g.hv(this.element,"ytp-autonav-cancelled-small-mode",this.Bg(a));g.hv(this.element,"ytp-autonav-cancelled-tiny-mode",this.BI(a));g.hv(this.element,"ytp-autonav-cancelled-mini-mode",400>=a.width||360>=a.height);this.overlay&&g.is(this.overlay.element,{width:a.width+"px"});if(!this.G)for(a=0;a<this.videos.length;a++)g.hv(this.videos[a].element,"ytp-suggestion-card-with-margin",1===a%2)};
g.k.onVideoDataChange=function(){var a=this.player.getVideoData();if(this.videoData!==a&&a){this.videoData=a;if((a=this.videoData.suggestions)&&a.length||this.player.L("web_player_autonav_empty_suggestions_fix")){var b=g.BT(this.videoData);b&&(this.j.fG(b),this.j!==this.B&&this.B.fG(b))}if(a&&a.length)for(b=0;b<lrb.length;++b){var c=lrb[b];if(a&&a[c]){this.videos[b]=new k6(this.player);var d=this.videos[b];c=a[c];d.suggestion!==c&&(d.suggestion=c,j6(d,c));g.J(this,this.videos[b]);this.videos[b].Ja(this.N.element)}}this.LB()}};
g.k.DS=function(a){1===a?(this.K=!1,this.C=this.videoData.clientPlaybackNonce,this.j.Qp(),this.Ib&&this.LB()):(this.K=!0,this.sf()&&(2===a?this.j.kB():3===a&&this.j.xw()))};
g.k.E1=function(a){a?this.DS(1):(this.C=null,this.K=!1)};
g.k.wC=function(){return 1!==this.videoData.autonavState};
g.k.Bg=function(a){return(910>a.width||459>a.height)&&!this.BI(a)&&!(400>=a.width||360>=a.height)};
g.k.BI=function(a){return 800>a.width&&!(400>=a.width||360>=a.height)};
g.k.sf=function(){return this.Ib&&g.IU(this.player)&&this.wC()&&!this.C};
var lrb=[1,3,2,4];g.w(r6,g.S);g.k=r6.prototype;g.k.e_=function(){switch(this.buttonType){case 1:var a="Watch again on YouTube";var b=156915;break;case 2:a="Continue watching on YouTube";b=156942;break;default:a="Continue watching on YouTube",b=156942}this.update({content:a});this.J.hasVe(this.element)&&this.J.destroyVe(this.element);this.J.createClientVe(this.element,this,b)};
g.k.onClick=function(a){this.J.L("web_player_log_click_before_generating_ve_conversion_params")&&this.J.logClick(this.element);g.dV(this.getVideoUrl(),this.J,a);this.J.L("web_player_log_click_before_generating_ve_conversion_params")||this.J.logClick(this.element)};
g.k.getVideoUrl=function(){var a=!0;switch(this.buttonType){case 1:a=!0;break;case 2:a=!1}a=this.J.getVideoUrl(a,!1,!1,!0);var b=this.J.U();if(g.oS(b)){var c={};g.oS(b)&&g.oU(this.J,"addEmbedsConversionTrackingParams",[c]);a:{switch(this.buttonType){case 2:b="emb_ytp_continue_watching";break a}b="emb_ytp_watch_again"}g.LP(c,b);a=g.Ql(a,c)}return a};
g.k.logVisibility=function(){this.J.logVisibility(this.element,this.Ib&&this.Z)};
g.k.show=function(){g.S.prototype.show.call(this);this.logVisibility()};
g.k.hide=function(){g.S.prototype.hide.call(this);this.logVisibility()};
g.k.Ic=function(a){g.S.prototype.Ic.call(this,a);this.logVisibility()};g.w(s6,n6);s6.prototype.show=function(){3!==this.player.getPlayerState()&&(n6.prototype.show.call(this),this.Re.bB(!0),this.Re.wr(!0),this.J.U().Qe||this.Re.vr(!0),this.J.logVisibility(this.element,!0),this.watchButton.Ic(!0))};
s6.prototype.hide=function(){n6.prototype.hide.call(this);this.Re.bB(!1);this.Re.wr(!1);this.Re.vr(!1);this.J.logVisibility(this.element,!1);this.watchButton.Ic(!1)};g.w(grb,n6);grb.prototype.Ra=function(){var a=this.player.getVideoData();this.j.update({profilePicture:a.profilePicture,author:a.author});this.subscribeButton.channelId=a.yl;var b=this.subscribeButton;a.subscribed?b.j():b.B()};g.w(t6,g.S);t6.prototype.select=function(){this.api.xo(this.suggestion.videoId,this.suggestion.sessionData,this.suggestion.playlistId,void 0,void 0,this.suggestion.QC||void 0)&&this.api.logClick(this.element)};
t6.prototype.onClick=function(a){if(g.oS(this.api.U())&&this.api.L("web_player_log_click_before_generating_ve_conversion_params")){this.api.logClick(this.element);var b=this.suggestion.Jk(),c={};g.GTa(this.api,c,"emb_rel_end");b=g.Ql(b,c);g.dV(b,this.api,a)}else g.cV(a,this.api,this.B,this.suggestion.sessionData||void 0)&&this.select()};
t6.prototype.onKeyPress=function(a){switch(a.keyCode){case 13:case 32:a.defaultPrevented||(this.select(),a.preventDefault())}};
t6.prototype.onVideoDataChange=function(){var a=this.api.getVideoData(),b=this.api.U();this.B=a.Hf?!1:b.D};g.w(u6,n6);g.k=u6.prototype;g.k.create=function(){n6.prototype.create.call(this);var a=this.player.getVideoData();a&&(this.videoData=a);this.Yp();this.B.T(this.player,"appresize",this.Yp);this.B.T(this.player,"onVideoAreaChange",this.Yp);this.B.T(this.player,"videodatachange",this.onVideoDataChange);this.B.T(this.player,"autonavchange",this.pL);this.B.T(this.player,"onAutonavCancelled",this.F1);a=this.videoData.autonavState;a!==this.W&&this.pL(a);this.B.T(this.element,"transitionend",this.V$)};
g.k.destroy=function(){g.$C(this.B);g.wb(this.stills);this.stills=[];n6.prototype.destroy.call(this);g.fv(this.element,"ytp-show-tiles");this.K.stop();this.W=this.videoData.autonavState};
g.k.wC=function(){return 1!==this.videoData.autonavState};
g.k.show=function(){var a=this.Ib;n6.prototype.show.call(this);g.fv(this.element,"ytp-show-tiles");this.player.U().B?g.Su(this.K):this.K.start();(this.G||this.D&&this.D!==this.videoData.clientPlaybackNonce)&&g.BU(this.player,!1);v6(this)?(w6(this),2===this.videoData.autonavState?3===this.player.getVisibilityState()?this.j.select(!0):this.j.kB():3===this.videoData.autonavState&&this.j.xw()):(g.BU(this.player,!0),w6(this));a!==this.Ib&&this.player.logVisibility(this.element,!0)};
g.k.hide=function(){var a=this.Ib;n6.prototype.hide.call(this);this.j.xw();w6(this);a!==this.Ib&&this.player.logVisibility(this.element,!1)};
g.k.V$=function(a){a.target===this.element&&this.Yp()};
g.k.Yp=function(){var a,b,c,d;var e=(null==(a=this.videoData)?0:null==(b=a.suggestions)?0:b.length)?null==(c=this.videoData)?void 0:c.suggestions:[null==(d=this.videoData)?void 0:g.BT(d)];if(e.length){g.dv(this.element,"ytp-endscreen-paginate");var f=this.J.hn(!0,this.J.isFullscreen());if(a=g.uU(this.J))a=a.nh()?48:32,f.width-=2*a;var h=f.width/f.height;d=96/54;b=a=2;var l=Math.max(f.width/96,2),m=Math.max(f.height/54,2);c=e.length;var n=Math.pow(2,2);var p=c*n+(Math.pow(2,2)-n);p+=Math.pow(2,2)-
n;for(p-=n;0<p&&(a<l||b<m);){var q=a/2,r=b/2,t=a<=l-2&&p>=r*n,v=b<=m-2&&p>=q*n;if((q+1)/r*d/h>h/(q/(r+1)*d)&&v)p-=q*n,b+=2;else if(t)p-=r*n,a+=2;else if(v)p-=q*n,b+=2;else break}d=!1;p>=3*n&&6>=c*n-p&&(4<=b||4<=a)&&(d=!0);n=96*a;p=54*b;h=n/p<h?f.height/p:f.width/n;h=Math.min(h,2);n=Math.floor(Math.min(f.width,n*h));p=Math.floor(Math.min(f.height,p*h));f=this.table.element;f.ariaLive="polite";g.ts(f,n,p);g.is(f,{marginLeft:n/-2+"px",marginTop:p/-2+"px"});this.j.fG(g.BT(this.videoData));this.j instanceof
l6&&m6(this.j);g.hv(this.element,"ytp-endscreen-takeover",v6(this));w6(this);n+=4;p+=4;h=0;f.ariaBusy="true";for(l=0;l<a;l++)for(m=0;m<b;m++)if(q=h,t=0,d&&l>=a-2&&m>=b-2?t=1:0===m%2&&0===l%2&&(2>m&&2>l?0===m&&0===l&&(t=2):t=2),q=g.ke(q+this.C,c),0!==t){r=this.stills[h];r||(r=new t6(this.player),this.stills[h]=r,f.appendChild(r.element));v=Math.floor(p*m/b);var x=Math.floor(n*l/a),B=Math.floor(p*(m+t)/b)-v-4,F=Math.floor(n*(l+t)/a)-x-4;g.os(r.element,x,v);g.ts(r.element,F,B);g.is(r.element,"transitionDelay",
(m+l)/20+"s");g.hv(r.element,"ytp-videowall-still-mini",1===t);g.hv(r.element,"ytp-videowall-still-large",2<t);t=Math.max(F,B);g.hv(r.element,"ytp-videowall-still-round-large",256<=t);g.hv(r.element,"ytp-videowall-still-round-medium",96<t&&256>t);g.hv(r.element,"ytp-videowall-still-round-small",96>=t);q=e[q];r.suggestion!==q&&(r.suggestion=q,t=r.api.U(),v=g.cv(r.element,"ytp-videowall-still-large")?"hqdefault.jpg":"mqdefault.jpg",j6(r,q,v),g.oS(t)&&!r.api.L("web_player_log_click_before_generating_ve_conversion_params")&&
(t=q.Jk(),v={},g.oU(r.api,"addEmbedsConversionTrackingParams",[v]),t=g.Ql(t,g.LP(v,"emb_rel_end")),r.updateValue("url",t)),(q=(q=q.sessionData)&&q.itct)&&r.api.setTrackingParams(r.element,q));h++}f.ariaBusy="false";g.hv(this.element,"ytp-endscreen-paginate",h<c);for(e=this.stills.length-1;e>=h;e--)a=this.stills[e],g.sf(a.element),g.vb(a);this.stills.length=h}};
g.k.onVideoDataChange=function(){var a=this.player.getVideoData();this.videoData!==a&&(this.C=0,this.videoData=a,this.Yp())};
g.k.G1=function(){this.C+=this.stills.length;this.Yp()};
g.k.H1=function(){this.C-=this.stills.length;this.Yp()};
g.k.sX=function(){return this.j.Nk()};
g.k.pL=function(a){1===a?(this.G=!1,this.D=this.videoData.clientPlaybackNonce,this.j.Qp(),this.Ib&&this.Yp()):(this.G=!0,this.Ib&&v6(this)&&(2===a?this.j.kB():3===a&&this.j.xw()))};
g.k.F1=function(a){if(a){for(a=0;a<this.stills.length;a++)this.J.logVisibility(this.stills[a].element,!0);this.pL(1)}else this.D=null,this.G=!1;this.Yp()};
g.k.sf=function(){return this.Ib&&v6(this)};g.w(x6,n6);x6.prototype.ED=function(){var a;return null==(a=this.j)?void 0:a.ED()};
x6.prototype.show=function(){if(3!==this.player.getPlayerState()){n6.prototype.show.call(this);var a=this.B;if(a){var b=this.j.ED();g.hv(this.element,"ytp-shorts-branded-ui",b);b?a.show():a.hide()}var c;null==(c=g.uU(this.player))||c.cB(!0);this.player.logVisibility(this.element,!0);this.watchButton.Ic(!0)}};
x6.prototype.hide=function(){n6.prototype.hide.call(this);var a;null==(a=g.uU(this.player))||a.cB(!1);this.player.logVisibility(this.element,!1);this.watchButton.Ic(!1)};g.w(krb,g.UV);g.k=krb.prototype;g.k.Ot=function(){var a=this.player.getVideoData(),b=a.mutedAutoplay;if((g.EU(this.player)||this.B)&&!b)return!0;var c;var d=!!((null==a?0:g.BT(a))||(null==a?0:null==(c=a.suggestions)?0:c.length));d=!hrb(this.player)||d;a=a.vj;c=this.player.dD();return d&&!a&&!c&&!b};
g.k.sf=function(){return this.endScreen.sf()};
g.k.A7=function(){return this.sf()?this.endScreen.sX():!1};
g.k.xa=function(){this.player.yf("endscreen");g.UV.prototype.xa.call(this)};
g.k.load=function(){var a=this.player.getVideoData();var b=a.transitionEndpointAtEndOfStream;if(b&&b.videoId){var c=this.player.Bb().Ee.get("heartbeat"),d=g.BT(a);!d||b.videoId!==d.videoId||a.nS?(this.player.xo(b.videoId,void 0,void 0,!0,!0,b),c&&c.LI("HEARTBEAT_ACTION_TRIGGER_AT_STREAM_END","HEARTBEAT_ACTION_TRANSITION_REASON_HAS_NEW_STREAM_TRANSITION_ENDPOINT"),a=!0):a=!1}else a=!1;a||(g.UV.prototype.load.call(this),this.endScreen.show())};
g.k.unload=function(){g.UV.prototype.unload.call(this);this.endScreen.hide();this.endScreen.destroy()};
g.k.onCueRangeEnter=function(a){this.Ot()&&(this.endScreen.created||this.endScreen.create(),"load"===a.getId()&&this.load())};
g.k.onCueRangeExit=function(a){"load"===a.getId()&&this.loaded&&this.unload()};
g.k.onVideoDataChange=function(){jrb(this);this.D&&irb(this)&&(this.endScreen&&(this.endScreen.hide(),this.endScreen.created&&this.endScreen.destroy(),this.endScreen.dispose()),this.j?this.endScreen=new p6(this.player):this.endScreen=new u6(this.player),g.J(this,this.endScreen),g.HU(this.player,this.endScreen.element,4))};g.TV("endscreen",krb);})(_yt_player);
